version: 2

before:
  hooks:
    - go tool templ generate

builds:
  - id: beacon-darwin
    main: ./cmd/beacon
    binary: beacon
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: beacon-linux-amd64
    main: ./cmd/beacon
    binary: beacon
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu
    goos:
      - linux
    goarch:
      - amd64
  - id: beacon-linux-arm64
    main: ./cmd/beacon
    binary: beacon
    ldflags:
      - -s -w -X main.version={{ .Version }}
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu
    goos:
      - linux
    goarch:
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - THIRD_PARTY_NOTICES.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
