services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.12
    container_name: beacon-clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - beacon-clickhouse-data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  beacon-clickhouse-data:
