// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func FilterBar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"flex flex-wrap items-center gap-3 p-3 bg-gray-800 rounded-lg border border-gray-700\"><div><label class=\"text-xs text-gray-500 block mb-1\" for=\"filter-from\">From</label> <input type=\"datetime-local\" id=\"filter-from\" name=\"from\" class=\"bg-gray-700 text-gray-200 text-sm rounded px-2 py-1 border border-gray-600 focus:border-blue-500 focus:outline-none\"></div><div><label class=\"text-xs text-gray-500 block mb-1\" for=\"filter-to\">To</label> <input type=\"datetime-local\" id=\"filter-to\" name=\"to\" class=\"bg-gray-700 text-gray-200 text-sm rounded px-2 py-1 border border-gray-600 focus:border-blue-500 focus:outline-none\"></div><div><label class=\"text-xs text-gray-500 block mb-1\" for=\"filter-session\">Session</label> <input type=\"text\" id=\"filter-session\" name=\"session_id\" placeholder=\"All sessions\" class=\"bg-gray-700 text-gray-200 text-sm rounded px-2 py-1 border border-gray-600 focus:border-blue-500 focus:outline-none w-32\"></div><div><label class=\"text-xs text-gray-500 block mb-1\" for=\"filter-event-kind\">Event Kind</label> <select id=\"filter-event-kind\" name=\"event_kind\" class=\"bg-gray-700 text-gray-200 text-sm rounded px-2 py-1 border border-gray-600 focus:border-blue-500 focus:outline-none\"><option value=\"\">All</option> <option value=\"message\">Message</option> <option value=\"tool_call\">Tool Call</option> <option value=\"tool_result\">Tool Result</option> <option value=\"reasoning\">Reasoning</option> <option value=\"error\">Error</option></select></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
